/**
 * Seed the research project: default agent settings and the initial research
 * themes as OPEN QUESTIONS (not conclusions). Idempotent.
 *
 *   pnpm db:seed           → apply to DATABASE_URL
 *   pnpm db:seed --sql     → print equivalent SQL (see supabase/seed.sql)
 */
import "dotenv/config";
import postgres from "postgres";
import { DEFAULT_SETTINGS, SEED_THEMES } from "../src/lib/settings/schema";

function lit(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function slug(theme: string): string {
  return theme.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

export function buildSeedSql(): string {
  const lines: string[] = ["-- Generated by `pnpm db:seed --sql`. Idempotent.", ""];
  for (const [key, value] of Object.entries(DEFAULT_SETTINGS)) {
    lines.push(
      `insert into agent_settings (key, value) values (${lit(key)}, ${lit(JSON.stringify(value))}::jsonb) on conflict (key) do nothing;`,
    );
  }
  lines.push("");
  for (const theme of SEED_THEMES) {
    const tag = slug(theme);
    const statement = `What does the evidence say about ${theme.charAt(0).toLowerCase()}${theme.slice(1)} in the context of partial reprogramming, rejuvenation and cancer risk?`;
    const metadata = JSON.stringify({ seedTheme: theme, note: "Seeded research direction; not an established conclusion." });
    lines.push(
      `insert into knowledge_nodes (type, statement, summary, status, origin, tags, metadata)
select 'question', ${lit(statement)}, ${lit(`Research theme: ${theme}`)}, 'open', 'operator', array[${lit("theme")}, ${lit(tag)}], ${lit(metadata)}::jsonb
where not exists (select 1 from knowledge_nodes where metadata->>'seedTheme' = ${lit(theme)});`,
    );
  }
  return lines.join("\n") + "\n";
}

async function main() {
  const text = buildSeedSql();
  if (process.argv.includes("--sql")) {
    process.stdout.write(text);
    return;
  }
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL is not set");
  const sql = postgres(url, { max: 1, prepare: false, onnotice: () => {} });
  try {
    await sql.unsafe(text);
    console.log("Seed applied.");
  } finally {
    await sql.end();
  }
}

if (process.argv[1]?.endsWith("seed.ts")) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
